### PR TITLE
Enable websockets transport

### PR DESCRIPTION
**Pull request by ivanovaleksey**

### CODE REVIEW

**Comment by mquander** [comment]
Just FYI, you might want to go read [this issue](https://github.com/meetecho/janus-gateway/pull/1060). I've observed deadlocks where Janus stops accepting websocket connections. (I'm not yet sure if compiling with `LWS_SMP_MAX=1` fixes them, but all the people in that thread thought it should.)

**Comment by ivanovaleksey** [comment]
Thank you @mquander,
currently I use websockets transport only in development mode and I haven't faced with the issue.
And what about you? Did compiling with `LWS_SMP_MAX=1` help you?

**Comment by mquander** [comment]
The deadlock hasn't recurred yet, but I've only been testing for a day or two with the option changed so I'm not very confident.

**Comment by ivanovaleksey** [comment]
By the way @mquander, it is `LWS_MAX_SMP=1` not `LWS_SMP_MAX` :)

**Pull request merged**
